# Generated by Django 5.2.17 on 2026-09-03 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_audit_fields'),
        ('tenants', '0003_membershipproperty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', 'O‘tkazma')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('approved', 'Tasdiqlangan'), ('paid', 'To‘langan'), ('rejected', 'Rad etilgan')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ProfitPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('share_percent', models.DecimalField(decimal_places=2, help_text='Masalan 30.00 — sof foydaning 30 foizi.', max_digits=6, verbose_name='Ulush %')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefon')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Foyda sherigi',
                'verbose_name_plural': 'Foyda sheriklari',
                'ordering': ['-share_percent', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProfitPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_on', models.DateField(verbose_name='Boshlanish')),
                ('ended_on', models.DateField(blank=True, null=True, verbose_name='Tugash')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('net_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_periods_closed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Foyda davri',
                'verbose_name_plural': 'Foyda davrlari',
                'ordering': ['-started_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProfitWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa')),
                ('paid_on', models.DateField(verbose_name='Sana')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', 'O‘tkazma')], default='cash', max_length=20, verbose_name='Usul')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_withdrawals_created', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='finance.profitpartner')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='finance.profitperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Foyda olish',
                'verbose_name_plural': 'Foyda olishlar',
                'ordering': ['-paid_on', '-id'],
            },
        ),
    ]
