# Generated by Django 5.2.17 on 2026-09-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_expense_funding_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitperiod',
            name='distributable_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='profitperiod',
            name='operating_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='profitperiod',
            name='receipt_snapshot',
            field=models.JSONField(blank=True, help_text='Yopilgandagi chek hisobot (tarix uchun).', null=True),
        ),
        migrations.AddField(
            model_name='profitperiod',
            name='reinvestment_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='profitperiod',
            name='revenue_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='funding',
            field=models.CharField(choices=[('operating', 'Joriy (Sofdan)'), ('reinvestment', 'Reinvestitsiya (foydadan)')], default='operating', help_text='Joriy — sof foydadan. Reinvestitsiya — sof foydaga tegmaydi, ulushi eng katta sherikning ulushidan ayiriladi.', max_length=20, verbose_name='Moliyalashtirish'),
        ),
    ]
