# Generated by Django 5.2.17 on 2026-09-01 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_branch_code_and_more'),
        ('tenants', '0002_two_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_assignments', to='tenants.tenantmembership')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='properties.property')),
            ],
            options={
                'verbose_name': 'Filial biriktirish',
                'verbose_name_plural': 'Filial biriktirishlar',
                'unique_together': {('membership', 'property')},
            },
        ),
    ]
