# Generated by Django 5.2.17 on 2026-09-06 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_hotel_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='currency',
            field=models.CharField(choices=[('UZS', 'So‘m (UZS)'), ('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)')], default='UZS', help_text='Bazaviy valyuta — hisobotlar, P&L, balans shu valyutada.', max_length=8),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('UZS', 'So‘m (UZS)'), ('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)')], max_length=3)),
                ('base_currency', models.CharField(choices=[('UZS', 'So‘m (UZS)'), ('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)')], default='UZS', max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('effective_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Valyuta kursi',
                'verbose_name_plural': 'Valyuta kurslari',
                'ordering': ['-effective_on', 'currency'],
                'unique_together': {('tenant', 'currency', 'base_currency', 'effective_on')},
            },
        ),
    ]
