# Generated by Django 5.2.17 on 2026-09-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_multicurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='base_currency',
            field=models.CharField(choices=[('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('UZS', 'So‘m (UZS)')], default='UZS', max_length=3),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('UZS', 'So‘m (UZS)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('UZS', 'So‘m (UZS)')], default='UZS', help_text='Bazaviy valyuta — hisobotlar, P&L, balans shu valyutada.', max_length=8),
        ),
    ]
