# Generated by Django 5.2.17 on 2026-09-04 11:29

from django.db import migrations, models


def sync_paid_at_from_created(apps, schema_editor):
    """Use created_at so same-day multi-shift cash reports stay accurate."""
    SalaryPayment = apps.get_model("hr", "SalaryPayment")
    for payment in SalaryPayment.objects.all().iterator():
        if payment.created_at:
            SalaryPayment.objects.filter(pk=payment.pk).update(paid_at=payment.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_advance_period_and_docs_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="salary_type",
            field=models.CharField(
                choices=[("monthly", "Oylik maosh"), ("daily", "Kunlik")],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Qoralama"),
                    ("finalized", "Yakunlangan"),
                    ("paid", "To‘langan"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salarypayment",
            name="paid_at",
            field=models.DateTimeField(),
        ),
        migrations.RunPython(sync_paid_at_from_created, migrations.RunPython.noop),
    ]
