# Generated by Django 5.2.17 on 2026-09-06 15:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_salary_payment_paid_at_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryadvance',
            name='amount_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Bazaviy valyutadagi summa (hisobotlar uchun)', max_digits=16),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='currency',
            field=models.CharField(choices=[('UZS', 'So‘m (UZS)'), ('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)')], db_index=True, default='UZS', max_length=3),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='1 birlik valyuta = fx_rate × bazaviy valyuta', max_digits=18),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='amount_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Bazaviy valyutadagi summa (hisobotlar uchun)', max_digits=16),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='currency',
            field=models.CharField(choices=[('UZS', 'So‘m (UZS)'), ('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)')], db_index=True, default='UZS', max_length=3),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='1 birlik valyuta = fx_rate × bazaviy valyuta', max_digits=18),
        ),
    ]
