# Generated by Django 5.2.17 on 2026-09-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_payrollitem_daily_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryadvance',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('UZS', 'So‘m (UZS)')], db_index=True, default='UZS', max_length=3),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('UZS', 'So‘m (UZS)')], db_index=True, default='UZS', max_length=3),
        ),
    ]
