# Generated by Django 5.2.17 on 2026-09-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='currency',
            field=models.CharField(choices=[('UZS', 'So‘m (UZS)'), ('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)')], default='UZS', max_length=3),
        ),
    ]
