# Generated by Django 5.2.17 on 2026-09-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_currency_accounting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('UZS', 'So‘m (UZS)')], default='UZS', max_length=3),
        ),
    ]
