# Generated by Django 5.2.17 on 2026-08-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysettings',
            name='require_id_on_checkin',
            field=models.BooleanField(default=False, help_text='Block check-in when guest has no passport/ID document.'),
        ),
    ]
