# Generated by Django 5.2.17 on 2026-08-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_require_id_on_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertysettings',
            name='require_id_on_checkin',
            field=models.BooleanField(default=True, help_text='Block check-in when guest has no passport/ID document.'),
        ),
    ]
