# Generated by Django 5.2.17 on 2026-09-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_advance_period_and_docs_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('ready', 'Tayyor'), ('dirty', 'Kir'), ('cleaning', 'Tozalanmoqda'), ('inspected', 'Tekshirilgan'), ('out_of_order', 'Nosoz')], default='ready', max_length=20),
        ),
    ]
