# Generated by Django 5.2.17 on 2026-09-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_room_status'),
        ('tenants', '0002_two_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='branch_code',
            field=models.SlugField(blank=True, help_text='Bron kodi va widget URL uchun: tsh, chilanzar', max_length=32, verbose_name='Filial kodi'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(condition=models.Q(('branch_code', ''), _negated=True), fields=('tenant', 'branch_code'), name='uniq_tenant_branch_code'),
        ),
    ]
