# Generated by Django 5.2.17 on 2026-09-05 12:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_populate_branch_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysettings',
            name='emehmon_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='E-mehmon ro‘yxatdan o‘tkazish to‘lovi (bron/kirishda).', max_digits=14),
        ),
    ]
