# Generated by Django 5.2.17 on 2026-09-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_emehmon_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateplan',
            name='currency',
            field=models.CharField(choices=[('UZS', 'So‘m (UZS)'), ('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)')], default='UZS', max_length=3),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='currency',
            field=models.CharField(choices=[('UZS', 'So‘m (UZS)'), ('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)')], default='UZS', max_length=3),
        ),
    ]
