# Generated by Django 5.2.17 on 2026-09-11 10:40

from decimal import Decimal
from django.db import migrations, models


def zero_no_show_fees(apps, schema_editor):
    PropertySettings = apps.get_model("properties", "PropertySettings")
    PropertySettings.objects.exclude(no_show_fee_percent=Decimal("0")).update(
        no_show_fee_percent=Decimal("0")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_emehmon_per_guest_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertysettings',
            name='no_show_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Eski sozlama; kelmaganda jarima yozilmaydi — to‘lov qaytariladi.', max_digits=5),
        ),
        migrations.RunPython(zero_no_show_fees, migrations.RunPython.noop),
    ]
