# Generated by Django 5.2.17 on 2026-09-13 16:01

import django.db.models.deletion
from django.db import migrations, models


def seed_sellable_types(apps, schema_editor):
    Room = apps.get_model("properties", "Room")
    through = Room.sellable_types.through
    rows = []
    for room in Room.objects.exclude(room_type_id=None).iterator():
        rows.append(through(room_id=room.pk, roomtype_id=room.room_type_id))
    if rows:
        through.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_no_show_fee_default_zero"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="sellable_types",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Shu jismoniy xonani qanday tur sifatida sotish mumkin "
                    "(masalan Twin va Double). Bo‘sh qoldirilsa faqat asosiy tur."
                ),
                related_name="sellable_in_rooms",
                to="properties.roomtype",
            ),
        ),
        migrations.RunPython(seed_sellable_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="rateplan",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "Dollar (USD)"),
                    ("EUR", "Euro (EUR)"),
                    ("UZS", "So‘m (UZS)"),
                ],
                default="UZS",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                help_text="Asosiy / default tur (taqvimda birinchi ko‘rsatiladi).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms",
                to="properties.roomtype",
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "Dollar (USD)"),
                    ("EUR", "Euro (EUR)"),
                    ("UZS", "So‘m (UZS)"),
                ],
                default="UZS",
                max_length=3,
            ),
        ),
    ]
