# Generated by Django 5.2.17 on 2026-08-26 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_reservationgroup_reservation_group'),
        ('folio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpayment',
            name='kind',
            field=models.CharField(choices=[('payment', 'Payment'), ('deposit', 'Deposit')], default='payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='folio',
            name='stay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folio', to='bookings.stay'),
        ),
    ]
