# Generated by Django 5.2.17 on 2026-09-04 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0004_city_ledger'),
        ('tenants', '0004_hotel_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinvoice',
            name='status',
            field=models.CharField(choices=[('open', 'Ochiq'), ('partial', 'Qisman'), ('paid', 'To‘langan'), ('void', 'Bekor')], default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='companypayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', 'O‘tkazma')], default='transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='foliocharge',
            name='charge_type',
            field=models.CharField(choices=[('room', 'Yashash'), ('service', 'Xizmat'), ('minibar', 'Minibar'), ('penalty', 'Jarima'), ('cancel', 'Bekor qilish to‘lovi'), ('other', 'Boshqa')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='guestpayment',
            name='kind',
            field=models.CharField(choices=[('payment', 'To‘lov'), ('deposit', 'Depozit'), ('city_ledger', 'Kompaniya hisobi')], default='payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='guestpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', 'O‘tkazma')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='CashShiftMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('pay_in', 'Kassa kirim'), ('pay_out', 'Kassa chiqim')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_shift_movements', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='folio.cashshift')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Kassa harakati',
                'verbose_name_plural': 'Kassa harakatlari',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
