# Generated by Django 5.2.17 on 2026-09-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0005_cash_shift_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foliocharge',
            name='charge_type',
            field=models.CharField(choices=[('room', 'Yashash'), ('service', 'Xizmat'), ('minibar', 'Minibar'), ('penalty', 'Jarima'), ('cancel', 'Bekor qilish to‘lovi'), ('emehmon', 'E-mehmon'), ('other', 'Boshqa')], default='other', max_length=20),
        ),
    ]
