# Generated by Django 5.2.17 on 2026-09-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0009_cashshift_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestpayment',
            name='kind',
            field=models.CharField(choices=[('payment', 'To‘lov'), ('deposit', 'Depozit'), ('refund', 'Sdachi / qaytarish'), ('city_ledger', 'Kompaniya hisobi')], default='payment', max_length=20),
        ),
    ]
