# Generated by Django 5.2.17 on 2026-09-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0010_alter_guestpayment_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashshiftmovement',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('UZS', 'So‘m (UZS)')], db_index=True, default='UZS', max_length=3),
        ),
        migrations.AlterField(
            model_name='companyinvoiceline',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('UZS', 'So‘m (UZS)')], db_index=True, default='UZS', max_length=3),
        ),
        migrations.AlterField(
            model_name='companypayment',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('UZS', 'So‘m (UZS)')], db_index=True, default='UZS', max_length=3),
        ),
        migrations.AlterField(
            model_name='foliocharge',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('UZS', 'So‘m (UZS)')], db_index=True, default='UZS', max_length=3),
        ),
        migrations.AlterField(
            model_name='guestpayment',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('UZS', 'So‘m (UZS)')], db_index=True, default='UZS', max_length=3),
        ),
    ]
