# Generated by Django 5.2.17 on 2026-08-31 06:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Alert when quantity on hand is at or below this level.', max_digits=12),
        ),
    ]
