# Generated by Django 5.2.17 on 2026-09-04 11:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_reorder_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Qoldiq shu qiymatga teng yoki past bo‘lsa ogohlantirish.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(choices=[('dona', 'Dona'), ('kg', 'Kg'), ('g', 'Gramm'), ('l', 'Litr'), ('ml', 'Ml'), ('quti', 'Quti'), ('paket', 'Paket'), ('juft', 'Juft'), ('m', 'Metr'), ('pcs', 'Dona (pcs)')], default='dona', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim'), ('adjust', 'Tuzatish')], max_length=16),
        ),
    ]
