# Generated by Django 5.2.17 on 2026-09-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_item_unit_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='expiry_alert_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Muddatdan shuncha kun oldin «yaqin» deb ogohlantiriladi.', verbose_name='Ogohlantirish (kun)'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Bo‘sh qoldirilsa muddat kuzatilmaydi.', null=True, verbose_name='Yaroqlilik muddati'),
        ),
    ]
