# Generated by Django 5.2.17 on 2026-10-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_stockitem_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='sku',
            field=models.CharField(max_length=80, verbose_name='SKU'),
        ),
    ]
