# Generated by Django 5.2.17 on 2026-10-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockitem_sku_free_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='photo',
            field=models.ImageField(blank=True, help_text='Ixtiyoriy. JPG, PNG yoki WEBP, 2 MB gacha.', upload_to='stock-photos/%Y/%m/', verbose_name='Rasm'),
        ),
    ]
