# Generated by Django 5.2.17 on 2026-10-06 12:49

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_cover_photos(apps, schema_editor):
    StockItem = apps.get_model("inventory", "StockItem")
    StockItemPhoto = apps.get_model("inventory", "StockItemPhoto")
    for item in StockItem.objects.exclude(photo="").exclude(photo__isnull=True):
        if not item.photo:
            continue
        StockItemPhoto.objects.get_or_create(
            item=item,
            image=item.photo,
            defaults={"tenant_id": item.tenant_id},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stockitem_photo'),
        ('tenants', '0007_tenant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='photo',
            field=models.ImageField(blank=True, help_text='Ixtiyoriy. Birinchi rasm ro‘yxatda ko‘rinadi.', upload_to='stock-photos/%Y/%m/', verbose_name='Rasm'),
        ),
        migrations.CreateModel(
            name='StockItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='stock-photos/%Y/%m/', verbose_name='Rasm')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.stockitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tovar rasmi',
                'verbose_name_plural': 'Tovar rasmlari',
                'ordering': ['pk'],
            },
        ),
        migrations.RunPython(copy_legacy_cover_photos, migrations.RunPython.noop),
    ]
