# Generated by Django 5.2.17 on 2026-08-26 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NightAuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_date', models.DateField()),
                ('posted_room_charges', models.PositiveIntegerField(default=0)),
                ('open_folios', models.PositiveIntegerField(default=0)),
                ('occupancy_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_audits', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-audit_date', '-id'],
                'unique_together': {('tenant', 'audit_date')},
            },
        ),
    ]
