# Generated by Django 5.2.17 on 2026-08-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightauditrun',
            name='dirty_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nightauditrun',
            name='no_shows_marked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nightauditrun',
            name='overdue_folios',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
