# Generated by Django 5.2.17 on 2026-09-01 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_branch_code_and_more'),
        ('reports', '0002_night_audit_cod'),
        ('tenants', '0003_membershipproperty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nightauditrun',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nightauditrun',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='night_audits', to='properties.property'),
        ),
        migrations.AlterUniqueTogether(
            name='nightauditrun',
            unique_together={('tenant', 'hotel', 'audit_date')},
        ),
    ]
