# Generated by Django 5.2.17 on 2026-09-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeepingtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('done', 'Bajarilgan')], default='pending', max_length=20),
        ),
    ]
