# Generated by Django 5.2.17 on 2026-08-29 14:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
