# Generated by Django 5.2.17 on 2026-09-03 07:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_city_ledger'),
        ('tenants', '0003_membershipproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Kompaniya', 'verbose_name_plural': 'Kompaniyalar'},
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='company',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Bo‘sh qoldirilsa 0.', max_digits=14, verbose_name='Kredit limiti'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True, max_length=32, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_terms_days',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='Bo‘sh qoldirilsa 30 kun.', verbose_name='To‘lov muddati (kun)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='guestdocument',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Pasport'), ('id_card', 'ID karta'), ('other', 'Boshqa')], default='passport', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='guests_company_tenant_name_uniq', violation_error_message='Bu mehmonxonada shu nomli kompaniya allaqachon mavjud. Boshqa nom tanlang yoki mavjud kompaniyani tahrirlang.'),
        ),
    ]
