# Generated by Django 5.2.17 on 2026-09-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_company_admin_ux'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
