# Generated by Django 5.2.17 on 2026-09-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Past'), ('medium', 'O‘rtacha'), ('high', 'Yuqori')], default='medium', max_length=16),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='status',
            field=models.CharField(choices=[('open', 'Ochiq'), ('in_progress', 'Jarayonda'), ('done', 'Bajarilgan'), ('cancelled', 'Bekor qilingan')], default='open', max_length=20),
        ),
    ]
