# Generated by Django 5.2.17 on 2026-09-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('free', 'Bepul'), ('basic', 'Asosiy'), ('pro', 'Pro')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Har oy'), ('yearly', 'Har yil')], default='monthly', max_length=16),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Sinov'), ('active', 'Faol'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=16),
        ),
    ]
