# Generated by Django 5.2.17 on 2026-09-04 12:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_reservationgroup_reservation_group'),
        ('tenants', '0004_hotel_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yo‘naltiruvchiga bron summasidan foiz.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='source',
            field=models.CharField(choices=[('walkin', 'Darhol'), ('phone', 'Telefon'), ('website', 'Veb-sayt'), ('other', 'Boshqa')], default='phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('inquiry', 'So‘rov'), ('confirmed', 'Tasdiqlangan'), ('checked_in', 'Joylashgan'), ('checked_out', 'Chiqgan'), ('cancelled', 'Bekor qilingan'), ('no_show', 'Kelmagan')], default='confirmed', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingReferrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('default_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Bron yaratilganda foiz shu qiymatdan to‘ldiriladi.', max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Yo‘naltiruvchi',
                'verbose_name_plural': 'Yo‘naltiruvchilar',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='bookings.bookingreferrer'),
        ),
    ]
