# Generated by Django 5.2.17 on 2026-09-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_commission_payment_and_payroll_adjust'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='currency',
            field=models.CharField(choices=[('UZS', 'So‘m (UZS)'), ('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)')], default='UZS', max_length=3),
        ),
    ]
