# Generated by Django 5.2.17 on 2026-09-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_emehmon_required_for_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='emehmon_required',
            field=models.BooleanField(default=True, help_text='True — E-mehmon: tarif × kecha × mehmon; False — bu bronda olinmaydi.'),
        ),
    ]
