# Generated by Django 5.2.17 on 2026-09-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_emehmon_required_default_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrercommissionpayment',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('UZS', 'So‘m (UZS)')], db_index=True, default='UZS', max_length=3),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('UZS', 'So‘m (UZS)')], default='UZS', max_length=3),
        ),
    ]
