# Generated by Django 5.2.17 on 2026-09-20 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_reservationoccupant'),
        ('tenants', '0007_tenant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationoccupant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
    ]
