from django.urls import path

from . import ops, ops_extra, parity, views

app_name = "api"

urlpatterns = [
    path("auth/login/", views.login, name="login"),
    path("auth/logout/", views.logout, name="logout"),
    path("me/", views.me, name="me"),
    path("board/", views.board, name="board"),
    path("today/", views.today, name="today"),
    path("inquiries/", ops.inquiries, name="inquiries"),
    path("calendar/", ops.calendar, name="calendar"),
    path("reports/flash/", ops.flash_report, name="flash_report"),
    path("reports/pnl/", parity.pnl_report, name="pnl_report"),
    path("reports/night-audit/", parity.night_audit_status, name="night_audit_status"),
    path("reports/night-audit/run/", parity.night_audit_run, name="night_audit_run"),
    path("reports/commission/", ops_extra.commission_report, name="commission_report"),
    path(
        "reports/commission/<int:pk>/pay/",
        ops_extra.commission_pay,
        name="commission_pay",
    ),
    path("inventory/items/", ops_extra.inventory_items, name="inventory_items"),
    path(
        "inventory/items/<int:pk>/adjust/",
        ops_extra.inventory_adjust,
        name="inventory_adjust",
    ),
    path("inventory/low-stock/", ops_extra.inventory_low_stock, name="inventory_low_stock"),
    path("referrers/", ops_extra.referrers, name="referrers"),
    path("referrers/create/", ops_extra.referrer_create, name="referrer_create"),
    path("hr/employees/", ops_extra.hr_employees, name="hr_employees"),
    path("hr/employees/<int:pk>/advance/", ops_extra.hr_advance, name="hr_advance"),
    path("hr/employees/<int:pk>/pay/", ops_extra.hr_pay, name="hr_pay"),
    path("hr/advances/", ops_extra.hr_advances, name="hr_advances"),
    path(
        "hr/advances/<int:pk>/settle/",
        ops_extra.hr_advance_settle,
        name="hr_advance_settle",
    ),
    path("maintenance/", ops.maintenance_list, name="maintenance_list"),
    path("maintenance/create/", ops.maintenance_create, name="maintenance_create"),
    path(
        "maintenance/<int:pk>/complete/",
        ops.maintenance_complete,
        name="maintenance_complete",
    ),
    path("charges/<int:pk>/void/", ops.void_charge, name="void_charge"),
    path("payments/<int:pk>/void/", ops.void_payment, name="void_payment"),
    path("folios/<int:pk>/receipt/", parity.folio_receipt, name="folio_receipt"),
    path("folios/<int:pk>/close/", parity.folio_close, name="folio_close"),
    path("folios/<int:pk>/split-pay/", parity.folio_split_pay, name="folio_split_pay"),
    path("folios/<int:pk>/to-company/", parity.folio_to_company, name="folio_to_company"),
    path("companies/", parity.companies, name="companies"),
    path("companies/create/", parity.company_create, name="company_create"),
    path("city-ledger/", parity.city_ledger, name="city_ledger"),
    path(
        "city-ledger/<int:pk>/pay/",
        parity.city_ledger_pay,
        name="city_ledger_pay",
    ),
    path("groups/", parity.groups, name="groups"),
    path("groups/create/", parity.group_create, name="group_create"),
    path("groups/<int:pk>/", parity.group_detail, name="group_detail"),
    path("expenses/", parity.expenses, name="expenses"),
    path("rooms/available/", views.rooms_available, name="rooms_available"),
    path("reservations/", views.reservation_create, name="reservation_create"),
    path("reservations/search/", views.reservation_search, name="reservation_search"),
    path("services/", views.service_list, name="service_list"),
    path("minibar/items/", ops.minibar_items, name="minibar_items"),
    path("guests/", ops.guest_list, name="guest_list"),
    path("guests/create/", ops.guest_create, name="guest_create"),
    path("guests/<int:pk>/", parity.guest_update, name="guest_detail"),
    path(
        "guests/<int:pk>/documents/",
        parity.guest_add_document,
        name="guest_add_document",
    ),
    path("housekeeping/", ops.housekeeping_board, name="housekeeping_board"),
    path(
        "housekeeping/tasks/<int:pk>/complete/",
        ops.housekeeping_complete,
        name="housekeeping_complete",
    ),
    path("rooms/<int:pk>/status/", views.room_set_status, name="room_set_status"),
    path("reservations/<int:pk>/", views.reservation_detail, name="reservation_detail"),
    path(
        "reservations/<int:pk>/check-in/",
        views.reservation_check_in,
        name="reservation_check_in",
    ),
    path(
        "reservations/<int:pk>/check-out/",
        views.reservation_check_out,
        name="reservation_check_out",
    ),
    path(
        "reservations/<int:pk>/payment/",
        views.reservation_payment,
        name="reservation_payment",
    ),
    path(
        "reservations/<int:pk>/deposit/",
        ops.reservation_deposit,
        name="reservation_deposit",
    ),
    path(
        "reservations/<int:pk>/refund/",
        ops.reservation_refund,
        name="reservation_refund",
    ),
    path(
        "reservations/<int:pk>/charge/",
        views.reservation_charge,
        name="reservation_charge",
    ),
    path(
        "reservations/<int:pk>/service/",
        views.reservation_service,
        name="reservation_service",
    ),
    path(
        "reservations/<int:pk>/minibar/",
        ops.reservation_minibar,
        name="reservation_minibar",
    ),
    path(
        "reservations/<int:pk>/emehmon/",
        parity.reservation_emehmon,
        name="reservation_emehmon",
    ),
    path(
        "reservations/<int:pk>/transfer/",
        views.reservation_transfer,
        name="reservation_transfer",
    ),
    path(
        "reservations/<int:pk>/extend/",
        views.reservation_extend,
        name="reservation_extend",
    ),
    path(
        "reservations/<int:pk>/amend/",
        ops.reservation_amend,
        name="reservation_amend",
    ),
    path(
        "reservations/<int:pk>/cancel/",
        views.reservation_cancel,
        name="reservation_cancel",
    ),
    path(
        "reservations/<int:pk>/no-show/",
        views.reservation_no_show,
        name="reservation_no_show",
    ),
    path(
        "reservations/<int:pk>/confirm/",
        ops.reservation_confirm,
        name="reservation_confirm",
    ),
    path(
        "reservations/<int:pk>/notes/",
        views.reservation_notes,
        name="reservation_notes",
    ),
    path("cash-shift/", views.cash_shift_status, name="cash_shift_status"),
    path("cash-shift/open/", views.cash_shift_open, name="cash_shift_open"),
    path("cash-shift/close/", views.cash_shift_close, name="cash_shift_close"),
    path(
        "cash-shift/movement/",
        ops.cash_shift_movement,
        name="cash_shift_movement",
    ),
    path("walk-in/", views.walk_in, name="walk_in"),
]
