from django.urls import path

from . import admin_parity, finance_parity, notify_parity, ops, ops_extra, ops_gaps, parity, print_parity, setup, views

app_name = "api"

urlpatterns = [
    path("auth/login/", views.login, name="login"),
    path("auth/logout/", views.logout, name="logout"),
    path("me/", views.me, name="me"),
    path("me/update/", views.me_update, name="me_update"),
    path("board/", views.board, name="board"),
    path("today/", views.today, name="today"),
    path("inquiries/", ops.inquiries, name="inquiries"),
    path("calendar/", ops.calendar, name="calendar"),
    path("reports/flash/", ops.flash_report, name="flash_report"),
    path("reports/flash/print/", print_parity.flash_print, name="flash_print"),
    path("reports/dashboard/", ops_gaps.dashboard_report, name="dashboard_report"),
    path("reports/history/", ops_gaps.report_history, name="report_history"),
    path("reports/pnl/", parity.pnl_report, name="pnl_report"),
    path("reports/pnl/print/", print_parity.pnl_print, name="pnl_print"),
    path("notifications/", notify_parity.notifications_list, name="notifications"),
    path(
        "notifications/dismiss/",
        notify_parity.notifications_dismiss,
        name="notifications_dismiss",
    ),
    path("reports/night-audit/", parity.night_audit_status, name="night_audit_status"),
    path("reports/night-audit/run/", parity.night_audit_run, name="night_audit_run"),
    path("reports/audit/", admin_parity.audit_log, name="audit_log"),
    path("reports/emehmon/", admin_parity.emehmon_report, name="emehmon_report"),
    path(
        "reports/emehmon/print/",
        print_parity.emehmon_statement_print,
        name="emehmon_print",
    ),
    path("reports/commission/", ops_extra.commission_report, name="commission_report"),
    path(
        "reports/commission/<int:pk>/print/",
        print_parity.commission_statement_print,
        name="commission_print",
    ),
    path(
        "reports/commission/<int:pk>/pay/",
        ops_extra.commission_pay,
        name="commission_pay",
    ),
    path("export/payments.csv/", admin_parity.export_payments_csv, name="export_payments_csv"),
    path("export/pnl.csv/", admin_parity.export_pnl_csv, name="export_pnl_csv"),
    path("export/ar.csv/", admin_parity.export_ar_csv, name="export_ar_csv"),
    path("staff/", admin_parity.staff_list, name="staff_list"),
    path("staff/meta/", admin_parity.staff_meta, name="staff_meta"),
    path("staff/invite/", admin_parity.staff_invite, name="staff_invite"),
    path("staff/<int:pk>/", admin_parity.staff_update, name="staff_update"),
    path("inventory/items/", ops_extra.inventory_items, name="inventory_items"),
    path("inventory/items/create/", ops_extra.inventory_create, name="inventory_create"),
    path(
        "inventory/items/<int:pk>/adjust/",
        ops_extra.inventory_adjust,
        name="inventory_adjust",
    ),
    path(
        "inventory/items/<int:pk>/update/",
        ops_extra.inventory_update,
        name="inventory_update",
    ),
    path("inventory/low-stock/", ops_extra.inventory_low_stock, name="inventory_low_stock"),
    path("referrers/", ops_extra.referrers, name="referrers"),
    path("referrers/create/", ops_extra.referrer_create, name="referrer_create"),
    path(
        "referrers/<int:pk>/",
        finance_parity.referrer_update,
        name="referrer_update",
    ),
    path("hr/employees/", ops_extra.hr_employees, name="hr_employees"),
    path("hr/employees/create/", ops_extra.hr_employee_create, name="hr_employee_create"),
    path(
        "hr/employees/<int:pk>/update/",
        ops_extra.hr_employee_update,
        name="hr_employee_update",
    ),
    path("hr/employees/<int:pk>/advance/", ops_extra.hr_advance, name="hr_advance"),
    path("hr/employees/<int:pk>/pay/", ops_extra.hr_pay, name="hr_pay"),
    path("hr/advances/", ops_extra.hr_advances, name="hr_advances"),
    path(
        "hr/advances/<int:pk>/settle/",
        ops_extra.hr_advance_settle,
        name="hr_advance_settle",
    ),
    path("hr/payroll/", ops_extra.hr_payroll_status, name="hr_payroll_status"),
    path("hr/payroll/generate/", ops_extra.hr_payroll_generate, name="hr_payroll_generate"),
    path(
        "hr/payroll/<int:pk>/finalize/",
        ops_extra.hr_payroll_finalize,
        name="hr_payroll_finalize",
    ),
    path("hr/payroll/pay-all/", ops_extra.hr_payroll_pay_all, name="hr_payroll_pay_all"),
    path("maintenance/", ops.maintenance_list, name="maintenance_list"),
    path("maintenance/create/", ops.maintenance_create, name="maintenance_create"),
    path(
        "maintenance/<int:pk>/complete/",
        ops.maintenance_complete,
        name="maintenance_complete",
    ),
    path(
        "maintenance/<int:pk>/assign/",
        ops.maintenance_assign,
        name="maintenance_assign",
    ),
    path(
        "maintenance/<int:pk>/cancel/",
        ops.maintenance_cancel,
        name="maintenance_cancel",
    ),
    path(
        "maintenance/<int:pk>/spend/",
        ops.maintenance_spend,
        name="maintenance_spend",
    ),
    path("setup/settings/", setup.property_settings, name="property_settings"),
    path(
        "setup/settings/update/",
        setup.property_settings_update,
        name="property_settings_update",
    ),
    path("setup/room-types/", setup.room_types, name="room_types"),
    path("setup/room-types/create/", setup.room_type_create, name="room_type_create"),
    path(
        "setup/room-types/<int:pk>/update/",
        setup.room_type_update,
        name="room_type_update",
    ),
    path("setup/rooms/", setup.rooms_admin, name="rooms_admin"),
    path("setup/rooms/create/", setup.room_create, name="room_create"),
    path(
        "setup/rooms/<int:pk>/update/",
        setup.room_update,
        name="room_update",
    ),
    path("setup/floors/", setup.floors_admin, name="floors_admin"),
    path(
        "setup/floors/<int:pk>/update/",
        setup.floor_update,
        name="floor_update",
    ),
    path("setup/services/", setup.services_catalog, name="services_catalog"),
    path(
        "setup/services/<int:pk>/update/",
        setup.service_update,
        name="service_update",
    ),
    path("setup/rate-plans/", setup.rate_plans, name="rate_plans"),
    path("setup/rate-plans/create/", setup.rate_plan_create, name="rate_plan_create"),
    path(
        "setup/rate-plans/<int:pk>/update/",
        setup.rate_plan_update,
        name="rate_plan_update",
    ),
    path(
        "setup/rate-plans/<int:pk>/seasons/",
        setup.rate_plan_season_create,
        name="rate_plan_season_create",
    ),
    path(
        "setup/rate-plans/<int:pk>/matrix/",
        finance_parity.rate_plan_matrix,
        name="rate_plan_matrix",
    ),
    path("charges/<int:pk>/void/", ops.void_charge, name="void_charge"),
    path("payments/<int:pk>/void/", ops.void_payment, name="void_payment"),
    path("folios/<int:pk>/receipt/", parity.folio_receipt, name="folio_receipt"),
    path("folios/<int:pk>/close/", parity.folio_close, name="folio_close"),
    path("folios/<int:pk>/split-pay/", parity.folio_split_pay, name="folio_split_pay"),
    path("folios/<int:pk>/to-company/", parity.folio_to_company, name="folio_to_company"),
    path("companies/", parity.companies, name="companies"),
    path("companies/create/", parity.company_create, name="company_create"),
    path("companies/<int:pk>/", finance_parity.company_update, name="company_update"),
    path("city-ledger/", parity.city_ledger, name="city_ledger"),
    path(
        "city-ledger/<int:pk>/",
        finance_parity.city_ledger_detail,
        name="city_ledger_detail",
    ),
    path(
        "city-ledger/<int:pk>/pay/",
        parity.city_ledger_pay,
        name="city_ledger_pay",
    ),
    path("fx/", finance_parity.fx_list, name="fx_list"),
    path("fx/create/", finance_parity.fx_create, name="fx_create"),
    path("fx/<int:pk>/delete/", finance_parity.fx_delete, name="fx_delete"),
    path("fx/sync-cbu/", finance_parity.fx_sync_cbu, name="fx_sync_cbu"),
    path("profit/", finance_parity.profit_ledger, name="profit_ledger"),
    path("profit/partners/", finance_parity.profit_partners, name="profit_partners"),
    path(
        "profit/partners/create/",
        finance_parity.profit_partner_create,
        name="profit_partner_create",
    ),
    path(
        "profit/partners/<int:pk>/",
        finance_parity.profit_partner_update,
        name="profit_partner_update",
    ),
    path("profit/withdraw/", finance_parity.profit_withdraw, name="profit_withdraw"),
    path("profit/reset/", finance_parity.profit_reset, name="profit_reset"),
    path("groups/", parity.groups, name="groups"),
    path("groups/create/", parity.group_create, name="group_create"),
    path("groups/<int:pk>/", parity.group_detail, name="group_detail"),
    path("expenses/", parity.expenses, name="expenses"),
    path("expenses/meta/", parity.expenses_meta, name="expenses_meta"),
    path("expenses/create/", parity.expense_create, name="expense_create"),
    path("expenses/<int:pk>/print/", print_parity.expense_print, name="expense_print"),
    path("expenses/<int:pk>/approve/", parity.expense_approve, name="expense_approve"),
    path("expenses/<int:pk>/pay/", parity.expense_pay, name="expense_pay"),
    path(
        "expenses/<int:pk>/reject/",
        finance_parity.expense_reject,
        name="expense_reject",
    ),
    path(
        "expenses/<int:pk>/reopen/",
        finance_parity.expense_reopen,
        name="expense_reopen",
    ),
    path(
        "expenses/<int:pk>/delete/",
        finance_parity.expense_delete,
        name="expense_delete",
    ),
    path(
        "expenses/categories/create/",
        finance_parity.expense_category_create,
        name="expense_category_create",
    ),
    path(
        "expenses/vendors/create/",
        finance_parity.expense_vendor_create,
        name="expense_vendor_create",
    ),
    path("rooms/available/", views.rooms_available, name="rooms_available"),
    path("reservations/", views.reservation_create, name="reservation_create"),
    path("reservations/search/", views.reservation_search, name="reservation_search"),
    path("reservations/list/", ops_gaps.reservations_list, name="reservations_list"),
    path("services/", views.service_list, name="service_list"),
    path("services/order/", ops_gaps.service_order_quick, name="service_order_quick"),
    path(
        "services/orders/",
        ops_gaps.service_orders_recent,
        name="service_orders_recent",
    ),
    path("minibar/items/", ops.minibar_items, name="minibar_items"),
    path("minibar/quick/", ops_gaps.minibar_quick, name="minibar_quick"),
    path("guests/", ops.guest_list, name="guest_list"),
    path("guests/create/", ops.guest_create, name="guest_create"),
    path("guests/<int:pk>/", parity.guest_update, name="guest_detail"),
    path(
        "guests/<int:pk>/documents/",
        parity.guest_add_document,
        name="guest_add_document",
    ),
    path("housekeeping/", ops.housekeeping_board, name="housekeeping_board"),
    path("housekeeping/staff/", ops.housekeeping_staff, name="housekeeping_staff"),
    path(
        "housekeeping/tasks/<int:pk>/assign/",
        ops.housekeeping_assign,
        name="housekeeping_assign",
    ),
    path(
        "housekeeping/tasks/<int:pk>/complete/",
        ops.housekeeping_complete,
        name="housekeeping_complete",
    ),
    path("rooms/<int:pk>/status/", views.room_set_status, name="room_set_status"),
    path("reservations/<int:pk>/", views.reservation_detail, name="reservation_detail"),
    path(
        "reservations/<int:pk>/check-in/",
        views.reservation_check_in,
        name="reservation_check_in",
    ),
    path(
        "reservations/<int:pk>/check-out/",
        views.reservation_check_out,
        name="reservation_check_out",
    ),
    path(
        "reservations/<int:pk>/payment/",
        views.reservation_payment,
        name="reservation_payment",
    ),
    path(
        "reservations/<int:pk>/deposit/",
        ops.reservation_deposit,
        name="reservation_deposit",
    ),
    path(
        "reservations/<int:pk>/refund/",
        ops.reservation_refund,
        name="reservation_refund",
    ),
    path(
        "reservations/<int:pk>/charge/",
        views.reservation_charge,
        name="reservation_charge",
    ),
    path(
        "reservations/<int:pk>/service/",
        views.reservation_service,
        name="reservation_service",
    ),
    path(
        "reservations/<int:pk>/minibar/",
        ops.reservation_minibar,
        name="reservation_minibar",
    ),
    path(
        "reservations/<int:pk>/emehmon/",
        parity.reservation_emehmon,
        name="reservation_emehmon",
    ),
    path(
        "reservations/<int:pk>/transfer/",
        views.reservation_transfer,
        name="reservation_transfer",
    ),
    path(
        "reservations/<int:pk>/extend/",
        views.reservation_extend,
        name="reservation_extend",
    ),
    path(
        "reservations/<int:pk>/amend/",
        ops.reservation_amend,
        name="reservation_amend",
    ),
    path(
        "reservations/<int:pk>/occupants/",
        ops.reservation_occupants,
        name="reservation_occupants",
    ),
    path(
        "reservations/<int:pk>/cancel/",
        views.reservation_cancel,
        name="reservation_cancel",
    ),
    path(
        "reservations/<int:pk>/no-show/",
        views.reservation_no_show,
        name="reservation_no_show",
    ),
    path(
        "reservations/<int:pk>/confirm/",
        ops.reservation_confirm,
        name="reservation_confirm",
    ),
    path(
        "reservations/<int:pk>/notes/",
        views.reservation_notes,
        name="reservation_notes",
    ),
    path("cash-shift/", views.cash_shift_status, name="cash_shift_status"),
    path("cash-shift/open/", views.cash_shift_open, name="cash_shift_open"),
    path("cash-shift/close/", views.cash_shift_close, name="cash_shift_close"),
    path(
        "cash-shift/movement/",
        ops.cash_shift_movement,
        name="cash_shift_movement",
    ),
    path(
        "cash-shift/history/",
        ops_gaps.cash_shift_history,
        name="cash_shift_history",
    ),
    path(
        "cash-shift/<int:pk>/print/",
        print_parity.cash_shift_print,
        name="cash_shift_print",
    ),
    path("walk-in/", views.walk_in, name="walk_in"),
]
