# Generated by Django 5.2.17 on 2026-09-01 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0004_alter_room_status'),
        ('tenants', '0002_two_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Widget yoqilgan')),
                ('allowed_domains', models.TextField(blank=True, help_text='Har qator: aida-hotel.uz (www siz ham ishlaydi)', verbose_name='Ruxsat etilgan domenlar')),
                ('public_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('auto_confirm', models.BooleanField(default=False, help_text='Yoqilsa — CONFIRMED; o‘chiq — resepsiya tasdiqlaydi (INQUIRY).', verbose_name='Avtomatik tasdiqlash')),
                ('auto_assign_room', models.BooleanField(default=True, verbose_name='Bo‘sh xonani avtomatik biriktirish')),
                ('welcome_title', models.CharField(blank=True, default='', max_length=200)),
                ('welcome_text', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(blank=True, help_text='Bo‘sh qoldirilsa — birinchi faol mehmonxona.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widget_configs', to='properties.property', verbose_name='Mehmonxona')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget_config', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Veb-bron widget',
                'verbose_name_plural': 'Veb-bron widgetlar',
            },
        ),
    ]
