# Generated by Django 5.2.17 on 2026-09-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0002_widget_per_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetconfig',
            name='allowed_domains',
            field=models.TextField(blank=True, help_text='Har qator: aida-hotel.uz', verbose_name='Ruxsat etilgan domenlar'),
        ),
        migrations.AlterField(
            model_name='widgetconfig',
            name='auto_assign_room',
            field=models.BooleanField(default=True, verbose_name='Xona biriktirish'),
        ),
        migrations.AlterField(
            model_name='widgetconfig',
            name='auto_confirm',
            field=models.BooleanField(default=False, verbose_name='Avtomatik tasdiqlash'),
        ),
    ]
